### PR TITLE
Add optional sec create

### PR DESCRIPTION
**Pull request by aljones15**

### CODE REVIEW

**Review by BigBlueHat — CHANGES_REQUESTED** [review]
I don't think we want optional tests to be optionally run. The should always be run (if we wrote them), but should be labelled/counted as optional--i.e. they should not be given the same wait as MUSTs.

So...not really keen on this approach. It also breaks up the spec-order based approach we've been using so far...which is another vote against this approach. Sorry...

**Comment by aljones15** [comment]
@BigBlueHat after the discussion on the office hours call, do we want to make an issue to run these tests once we have a new feature in the reporter that marks tests as optional?

**Comment by BigBlueHat** [comment]
> @BigBlueHat after the discussion on the office hours call, do we want to make an issue to run these tests once we have a new feature in the reporter that marks tests as optional?

Yes. Let's get that feature into the reporter (`skipReason` or whatever). There are a number of reasons why tests are skipped and it'd be helpful to tell them apart. Thanks!

**Review by BigBlueHat — APPROVED** [review]
I still think we need to revisit this approach, but approving to keep things moving.

**Pull request merged**
